config/routes.rb
# frozen_string_literal: true

Strails::Engine.routes.draw do
  scope module: :backend, path: :admin, as: :backend do
    post "/change_locale", to: "locale#change_locale", as: :change_locale
    get "/dashboard", to: "dashboard#index", as: :dashboard
    resources :products do
      resources :variants
    end
    resources :option_types do
      resources :option_values
    end

    root to: redirect("admin/dashboard")
  end

  scope module: :frontend do
    post "/change_locale", to: "locale#change_locale", as: :change_locale
    root to: "home#index"
  end
end

app/models/strails/product.rb
# frozen_string_literal: true

module Strails
  class Product < ApplicationRecord
    attr_accessor :option_values

    with_options class_name: "Strails::Variant", inverse_of: :product do
      has_many :variants_including_master, dependent: :destroy
      has_many :variants, -> { where(is_master: false) }
      has_one :master, -> { where(is_master: true) }
    end

    validates :name, :master, presence: true

    after_initialize :build_master, unless: :master
    after_create :generate_variants, if: :option_values
    before_destroy :set_destroyed_by_product_in_variants, prepend: true

    delegate :sku, :price, to: :master

    accepts_nested_attributes_for :master

    def option_types
      variants.map(&:option_types).flatten.uniq
    end

    private

    def generate_variants
      combinations = generate_option_value_combinations(option_values)

      combinations.each do |combination|
        variants.create(option_values: combination)
      end
    end

    def generate_option_value_combinations(option_values)
      grouped = option_values.group_by(&:option_type).values

      return option_values.map { |ov| [ov] } if grouped.size == 1

      grouped.inject(grouped.shift) do |memo, value|
        memo.product(value).map(&:flatten)
      end
    end

    def set_destroyed_by_product_in_variants
      variants_including_master.each do |variant|
        variant.destroyed_by_product = true
      end
    end
  end
end

app/controllers/strails/backend/dashboard_controller.rb
# frozen_string_literal: true

require_dependency "strails/backend_controller"

module Strails
  module Backend
    class DashboardController < BackendController
      def index; end
    end
  end
end

app/controllers/strails/backend/option_types_controller.rb
# frozen_string_literal: true

require_dependency "strails/backend_controller"

module Strails
  module Backend
    class OptionTypesController < BackendController
      before_action :set_option_type, only: %i[show edit update destroy]

      def index
        @option_types = OptionType.all
      end

      def show
        redirect_to edit_backend_option_type_path(@option_type)
      end

      def new
        @option_type = OptionType.new
      end

      def edit; end

      def create
        @option_type = OptionType.new(option_type_params)

        if @option_type.save
          redirect_to backend_option_type_path(@option_type),
                      notice: t("successfully_created", model_name: translated_model_name("option_type"))
        else
          render :new
        end
      end

      def update
        if @option_type.update(option_type_params)
          redirect_to backend_option_type_path(@option_type),
                      notice: t("successfully_updated", model_name: translated_model_name("option_type"))
        else
          render :edit
        end
      end

      def destroy
        if @option_type.destroy
          redirect_to backend_option_types_path,
                      notice: t("successfully_destroyed", model_name: translated_model_name("option_type"))
        else
          redirect_to backend_option_type_path(@option_type),
                      error: t("errors.could_not_destroy", model_name: translated_model_name("option_type"))
        end
      end

      private

      def set_option_type
        @option_type = OptionType.find(params[:id])
      end

      def option_type_params
        params.require(:option_type).permit(:name, :presentation,
                                            option_values_attributes: %i[id name presentation _destroy])
      end
    end
  end
end

app/controllers/strails/backend/option_values_controller.rb
# frozen_string_literal: true

require_dependency "strails/backend_controller"

module Strails
  module Backend
    class OptionValuesController < BackendController
      before_action :set_option_type
      before_action :set_option_value, only: %i[show edit update destroy]

      def index
        @option_values = @option_type.option_values
      end

      def show
        redirect_to edit_backend_option_type_option_value_path(@option_type, @option_value)
      end

      def new
        @option_value = @option_type.option_values.build
      end

      def edit; end

      def create
        @option_value = @option_type.option_values.build(option_value_params)

        if @option_value.save
          redirect_to backend_option_type_option_values_path(@option_type),
                      notice: t("successfully_created", model_name: translated_model_name("option_value"))
        else
          render :new
        end
      end

      def update
        if @option_value.update(option_value_params)
          redirect_to backend_option_type_option_value_path(@option_type, @option_value),
                      notice: t("successfully_updated", model_name: translated_model_name("option_value"))
        else
          render :edit
        end
      end

      def destroy
        if @option_value.destroy
          redirect_to backend_option_type_option_values_path(@option_type),
                      notice: t("successfully_destroyed", model_name: translated_model_name("option_value"))
        else
          redirect_to backend_option_type_option_value_path(@option_type, @option_value),
                      error: t("errors.could_not_destroy", model_name: translated_model_name("option_value"))
        end
      end

      private

      def set_option_type
        @option_type = OptionType.find(params[:option_type_id])
      end

      def set_option_value
        @option_value = @option_type.option_values.find(params[:id])
      end

      def option_value_params
        params.require(:option_value).permit(:name, :presentation)
      end
    end
  end
end

app/controllers/strails/backend/products_controller.rb
# frozen_string_literal: true

require_dependency "strails/backend_controller"

module Strails
  module Backend
    class ProductsController < BackendController
      before_action :set_product, only: %i[show edit update destroy]
      before_action :set_grouped_option_values, only: %i[new create]

      def index
        @products = Product.all
      end

      def new
        @product = Product.new
      end

      def show
        redirect_to edit_backend_product_path(@product)
      end

      def edit; end

      def create
        @product = Product.new(product_params)

        option_values = OptionValue.where(id: option_value_params[:option_value_ids])
        @product.option_values = option_values unless option_values.empty?

        if @product.save
          redirect_to backend_product_path(@product),
                      notice: t("successfully_created", model_name: translated_model_name("product"))
        else
          render :new
        end
      end

      def update
        if @product.update(product_params)
          redirect_to backend_product_path(@product),
                      notice: t("successfully_updated", model_name: translated_model_name("product"))
        else
          render :edit
        end
      end

      def destroy
        if @product.destroy
          redirect_to backend_products_path,
                      notice: t("successfully_destroyed", model_name: translated_model_name("product"))
        else
          redirect_to backend_product_path(@product),
                      error: t("errors.could_not_destroy", model_name: translated_model_name("product"))
        end
      end

      private

      def set_product
        @product = Product.find(params[:id])
      end

      def set_grouped_option_values
        @grouped_option_values = OptionValue.all.group_by(&:option_type)
      end

      def product_params
        params.require(:product).permit(:name, :description, master_attributes: %i[id sku price])
      end

      def option_value_params
        params.require(:product).permit(option_value_ids: [])
      end
    end
  end
end

app/controllers/strails/backend/variants_controller.rb
# frozen_string_literal: true

require_dependency "strails/backend_controller"

module Strails
  module Backend
    class VariantsController < BackendController
      before_action :set_product
      before_action :set_variant, only: %i[show edit update destroy]

      def index
        @variants = @product.variants
      end

      def show
        redirect_to edit_backend_product_variant_path(@product, @variant)
      end

      def new
        @variant = @product.variants.build
        @option_values = OptionValue.all
      end

      def edit; end

      def create
        @variant = @product.variants.build(variant_params)

        option_values = OptionValue.where(id: option_value_params[:option_value_ids])
        @variant.option_values = option_values unless option_values.empty?

        if @variant.save
          redirect_to backend_product_variants_path(@product),
                      notice: t("successfully_created", model_name: translated_model_name("variant"))
        else
          @option_values = OptionValue.all
          render :new
        end
      end

      def update
        if @variant.update(variant_params)
          redirect_to backend_product_variant_path(@product, @variant),
                      notice: t("successfully_updated", model_name: translated_model_name("variant"))
        else
          render :edit
        end
      end

      def destroy
        if @variant.destroy
          redirect_to backend_product_variants_path(@product),
                      notice: t("successfully_destroyed", model_name: translated_model_name("variant"))
        else
          redirect_to backend_product_variant_path(@product, @variant),
                      error: t("errors.could_not_destroy", model_name: translated_model_name("variant"))
        end
      end

      private

      def set_variant
        @variant = @product.variants.find(params[:id])
      end

      def set_product
        @product = Product.find(params[:product_id])
      end

      def variant_params
        params.require(:variant).permit(:sku, :price)
      end

      def option_value_params
        params.require(:variant).permit(option_value_ids: [])
      end
    end
  end
end

app/controllers/strails/backend_controller.rb
# frozen_string_literal: true

require_dependency "strails/application_controller"

module Strails
  class BackendController < ApplicationController
    include Croutons::Controller

    layout "strails/backend"
  end
end

app/helpers/strails/backend/dashboard_helper.rb
# frozen_string_literal: true

module Strails
  module Backend
    module DashboardHelper
    end
  end
end

app/helpers/strails/backend/option_types_helper.rb
# frozen_string_literal: true

module Strails
  module Backend
    module OptionTypesHelper
    end
  end
end

app/helpers/strails/backend/option_values_helper.rb
# frozen_string_literal: true

module Strails
  module Backend
    module OptionValuesHelper
    end
  end
end

app/helpers/strails/backend/products_helper.rb
# frozen_string_literal: true

module Strails
  module Backend
    module ProductsHelper
      def option_type_checkbox(form, option_type)
        id = option_type.id
        checkbox_id = "option-type-#{id}-checkbox"
        onclick = "checkOptionValues(#{id})"

        checkbox = form.check_box("option_type_#{id}",
                                  { class: "form-check-input", id: checkbox_id, onclick: onclick },
                                  id,
                                  nil)
        label = form.label(checkbox_id,
                           content_tag(:strong, option_type.pretty_name),
                           class: "form-check-label")
        checkbox + label
      end

      def option_value_checkboxes(form, option_values)
        option_type_id = option_values.first.option_type.id
        list_id = "option-values-for-option-type-#{option_type_id}"

        content_tag(:ul, class: "list-unstyled mb-3 pl-3", id: list_id) do
          capture do
            option_values.each do |option_value|
              concat(content_tag(:li, option_value_checkbox(form, option_value)))
            end
          end
        end
      end

      def option_value_checkbox(form, option_value)
        id = option_value.id
        checkbox_id = "option-value-#{id}-checkbox"
        onclick = "checkOptionType(#{option_value.option_type.id})"

        checkbox = form.check_box(:option_value_ids,
                                  { multiple: true, class: "form-check-input", id: checkbox_id, onclick: onclick },
                                  id,
                                  nil)
        label = form.label(checkbox_id,
                           option_value.pretty_name,
                           class: "form-check-label")
        checkbox + label
      end
    end
  end
end

app/helpers/strails/backend/variants_helper.rb
# frozen_string_literal: true

require "byebug"

module Strails
  module Backend
    module VariantsHelper
      def display_variant_extra_price(variant)
        extra_price = variant.extra_price
        return if extra_price.zero?

        content_tag(:span, class: extra_price.positive? ? "text-success" : "text-danger") do
          "#{'+' if extra_price.positive?}#{number_to_currency(extra_price)}"
        end
      end
    end
  end
end

app/helpers/strails/backend_helper.rb
# frozen_string_literal: true

module Strails
  module BackendHelper
  end
end

app/views/strails/backend/products/_form.html.erb
<%= form_with(model: [:backend, product], local: true) do |form| %>
  <%= error_messages_for(product) %>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control", autocomplete: "off" %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control", size: "0x10" %>
      </div>
    </div>

    <div class="col-sm-6">
      <%= form.fields_for :master do |master_form| %>
        <div class="form-group">
          <%= master_form.label :sku %>
          <%= master_form.text_field :sku, class: "form-control", autocomplete: "off" %>
        </div>

        <div class="form-group">
          <%= master_form.label :price %>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">$</span>
            </div>
            <%= master_form.number_field :price, step: "0.01", class: "form-control", autocomplete: "off" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <% if @product.new_record? %>
    <div class="option-values-form">
      <%= render "option_values_form", form: form, grouped_option_values: @grouped_option_values %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit class: "btn-submit" %>

    <% if product.persisted? %>
      <%= link_to(backend_product_path(product), method: :delete, class: "btn-destroy ml-3") do %>
        <%= material_icon "delete" %> <%= t("destroy") %>
      <% end %>
    <% end %>

    <%= link_to(backend_products_path, class: "btn-cancel ml-3") do %>
      <%= material_icon "clear" %> <%= t("cancel") %>
    <% end %>
  </div>
<% end %>

<script>
  function parameterize(str) {
    return str.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
  }

  $(document).ready(function() {
    let sku_field = $("#product_master_attributes_sku")
    let name_field = $("#product_name")

    name_field.bind('input', function() {

      if (!sku_field.attr('data-custom')) {
        sku_field.val(parameterize(name_field.val()))
      }
    })

    sku_field.bind('input', function() {
      sku_field.attr('data-custom', sku_field.val() != "")
    })
  })
</script>

app/views/strails/backend/products/_option_values_form.html.erb
<% if grouped_option_values.empty? %>
  <div class="alert alert-info"><%= t("alerts.no_records_yet", plural_model_name: translated_model_name("option_value", plural: true)) %></div>
<% else %>
  <div class="card">
    <div class="card-header"><%= translated_model_name("option_value", plural: true) %></div>
    <div class="card-body">
      <div class="row">
        <% grouped_option_values.each do |option_type, option_values| %>
          <div class="col-lg-3 col-sm-6">
            <%= option_type_checkbox(form, option_type) %>
            <%= option_value_checkboxes(form, option_values) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<script>
  function checkOptionValues(id) {
    let checked = $(`#option-type-${id}-checkbox`).prop('checked')
    $(`#option-values-for-option-type-${id} .form-check-input`).prop('checked', checked)
  }

  function checkOptionType(id) {
    let some_checked = $(`#option-values-for-option-type-${id} .form-check-input:checked`).length > 0
    $(`#option-type-${id}-checkbox`).prop('checked', some_checked)
  }
</script>

app/views/strails/backend/products/edit.html.erb
<div class="product">
  <div class="card">
    <div class="card-header">
      <h3><%= @product.name %></h3>
    </div>
    <div class="card-body">
      <%= render 'form', product: @product %>
    </div>
  </div>
</div>

<%= content_for :content_navigation do %>
  <%= active_link_to(edit_backend_product_path(@product), active: :exact) do %>
    <%= material_icon "edit" %> <%= t("details") %>
  <% end %>
  <%= active_link_to(backend_product_variants_path(@product), active: :inclusive) do %>
    <%= material_icon "view_list" %> <%= translated_model_name("variant", plural: true) %>
  <% end %>
<% end %>

app/views/strails/backend/products/index.html.erb
<div class="products">
  <div class="card">
    <div class="card-header">
      <h3><%= translated_model_name("product", plural: true) %></h3>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th class="sku"><%= translated_model_attribute("variant", "sku") %></th>
              <th class="name"><%= translated_model_attribute("product", "name") %></th>
              <th class="description"><%= translated_model_attribute("product", "description") %></th>
              <th class="price"><%= translated_model_attribute("variant", "price") %></th>
              <th class="actions actions-2"><%= t("actions") %></th>
            </tr>
          </thead>

          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td class="sku"><%= product.sku %></td>
                <td class="name"><%= product.name %></td>
                <td class="description"><%= product.description %></td>
                <td class="price"><%= number_to_currency(product.price) %></td>
                <td class="actions actions-2">
                  <%= link_to material_icon("edit"), edit_backend_product_path(product), class: "btn-edit btn-sm" %>
                  <%= link_to material_icon("delete"), backend_product_path(product), method: :delete, class: "btn-destroy btn-sm" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <%= link_to t("new_product"), new_backend_product_path, class: "btn-new" %>
    </div>
  </div>
</div>

app/views/strails/backend/products/new.html.erb
<div class="product">
  <div class="card">
    <div class="card-header">
      <h3><%= t("new_product") %></h3>
    </div>
    <div class="card-body">
      <%= render 'form', product: @product %>
    </div>
  </div>
</div>