config/routes.rb
# frozen_string_literal: true

Strails::Engine.routes.draw do
  scope module: :backend, path: :admin, as: :backend do
    post "/change_locale", to: "locale#change_locale", as: :change_locale
    get "/dashboard", to: "dashboard#index", as: :dashboard
    resources :products do
      resources :variants
    end
    resources :option_types do
      resources :option_values
    end

    root to: redirect("admin/dashboard")
  end

  scope module: :frontend do
    post "/change_locale", to: "locale#change_locale", as: :change_locale
    root to: "home#index"
  end
end

app/models/strails/variant.rb
# frozen_string_literal: true

module Strails
  class Variant < ApplicationRecord
    attr_accessor :destroyed_by_product

    belongs_to :product
    has_many :option_value_variants, dependent: :destroy, inverse_of: :variant
    has_many :option_values, through: :option_value_variants

    validates :product, presence: true
    validates :option_values, presence: { unless: :is_master }
    validates :is_master, inclusion: { in: [true, false] }
    validate :only_one_option_value_per_option_type

    before_save :set_default_sku
    before_save :set_default_price
    before_destroy :dont_unless_destroyed_by_product, if: :is_master, prepend: true

    delegate :name, :description, to: :product

    def option_value_from_option_type(option_type)
      option_values.find_by(option_type: option_type)
    end

    def option_types
      option_values.map(&:option_type)
    end

    def extra_price
      price - product.price
    end

    def price
      if is_master
        super
      else
        product.price + (super.nil? ? 0 : super)
      end
    end

    def price=(value)
      if is_master
        super((value.nil? ? 0 : value.to_d))
      else
        super((value.nil? ? 0 : value.to_d) - (product.nil? ? 0 : product.price))
      end
    end

    private

    def only_one_option_value_per_option_type
      return if option_types == option_types.uniq

      errors.add(:option_values,
                 :cant_add_more_than_one_option_value_of_the_same_option_type,
                 message: I18n.t("errors.cant_set_more_than_one_option_value_of_the_same_option_type"))
    end

    def set_default_sku
      self.sku ||= ([product.sku] + option_values.map(&:name)).join(" ").parameterize.downcase
    end

    def set_default_price
      self.price ||= is_master? ? 0 : product.price
    end

    def dont_unless_destroyed_by_product
      return if destroyed_by_product

      errors.add(:base, :cant_destroy_master_variant, message: I18n.t("errors.cant_destroy_master_variant"))
      throw(:abort)
    end
  end
end

app/controllers/strails/backend/dashboard_controller.rb
# frozen_string_literal: true

require_dependency "strails/backend_controller"

module Strails
  module Backend
    class DashboardController < BackendController
      def index; end
    end
  end
end

app/controllers/strails/backend/option_types_controller.rb
# frozen_string_literal: true

require_dependency "strails/backend_controller"

module Strails
  module Backend
    class OptionTypesController < BackendController
      before_action :set_option_type, only: %i[show edit update destroy]

      def index
        @option_types = OptionType.all
      end

      def show
        redirect_to edit_backend_option_type_path(@option_type)
      end

      def new
        @option_type = OptionType.new
      end

      def edit; end

      def create
        @option_type = OptionType.new(option_type_params)

        if @option_type.save
          redirect_to backend_option_type_path(@option_type),
                      notice: t("successfully_created", model_name: translated_model_name("option_type"))
        else
          render :new
        end
      end

      def update
        if @option_type.update(option_type_params)
          redirect_to backend_option_type_path(@option_type),
                      notice: t("successfully_updated", model_name: translated_model_name("option_type"))
        else
          render :edit
        end
      end

      def destroy
        if @option_type.destroy
          redirect_to backend_option_types_path,
                      notice: t("successfully_destroyed", model_name: translated_model_name("option_type"))
        else
          redirect_to backend_option_type_path(@option_type),
                      error: t("errors.could_not_destroy", model_name: translated_model_name("option_type"))
        end
      end

      private

      def set_option_type
        @option_type = OptionType.find(params[:id])
      end

      def option_type_params
        params.require(:option_type).permit(:name, :presentation,
                                            option_values_attributes: %i[id name presentation _destroy])
      end
    end
  end
end

app/controllers/strails/backend/option_values_controller.rb
# frozen_string_literal: true

require_dependency "strails/backend_controller"

module Strails
  module Backend
    class OptionValuesController < BackendController
      before_action :set_option_type
      before_action :set_option_value, only: %i[show edit update destroy]

      def index
        @option_values = @option_type.option_values
      end

      def show
        redirect_to edit_backend_option_type_option_value_path(@option_type, @option_value)
      end

      def new
        @option_value = @option_type.option_values.build
      end

      def edit; end

      def create
        @option_value = @option_type.option_values.build(option_value_params)

        if @option_value.save
          redirect_to backend_option_type_option_values_path(@option_type),
                      notice: t("successfully_created", model_name: translated_model_name("option_value"))
        else
          render :new
        end
      end

      def update
        if @option_value.update(option_value_params)
          redirect_to backend_option_type_option_value_path(@option_type, @option_value),
                      notice: t("successfully_updated", model_name: translated_model_name("option_value"))
        else
          render :edit
        end
      end

      def destroy
        if @option_value.destroy
          redirect_to backend_option_type_option_values_path(@option_type),
                      notice: t("successfully_destroyed", model_name: translated_model_name("option_value"))
        else
          redirect_to backend_option_type_option_value_path(@option_type, @option_value),
                      error: t("errors.could_not_destroy", model_name: translated_model_name("option_value"))
        end
      end

      private

      def set_option_type
        @option_type = OptionType.find(params[:option_type_id])
      end

      def set_option_value
        @option_value = @option_type.option_values.find(params[:id])
      end

      def option_value_params
        params.require(:option_value).permit(:name, :presentation)
      end
    end
  end
end

app/controllers/strails/backend/products_controller.rb
# frozen_string_literal: true

require_dependency "strails/backend_controller"

module Strails
  module Backend
    class ProductsController < BackendController
      before_action :set_product, only: %i[show edit update destroy]
      before_action :set_grouped_option_values, only: %i[new create]

      def index
        @products = Product.all
      end

      def new
        @product = Product.new
      end

      def show
        redirect_to edit_backend_product_path(@product)
      end

      def edit; end

      def create
        @product = Product.new(product_params)

        option_values = OptionValue.where(id: option_value_params[:option_value_ids])
        @product.option_values = option_values unless option_values.empty?

        if @product.save
          redirect_to backend_product_path(@product),
                      notice: t("successfully_created", model_name: translated_model_name("product"))
        else
          render :new
        end
      end

      def update
        if @product.update(product_params)
          redirect_to backend_product_path(@product),
                      notice: t("successfully_updated", model_name: translated_model_name("product"))
        else
          render :edit
        end
      end

      def destroy
        if @product.destroy
          redirect_to backend_products_path,
                      notice: t("successfully_destroyed", model_name: translated_model_name("product"))
        else
          redirect_to backend_product_path(@product),
                      error: t("errors.could_not_destroy", model_name: translated_model_name("product"))
        end
      end

      private

      def set_product
        @product = Product.find(params[:id])
      end

      def set_grouped_option_values
        @grouped_option_values = OptionValue.all.group_by(&:option_type)
      end

      def product_params
        params.require(:product).permit(:name, :description, master_attributes: %i[id sku price])
      end

      def option_value_params
        params.require(:product).permit(option_value_ids: [])
      end
    end
  end
end

app/controllers/strails/backend/variants_controller.rb
# frozen_string_literal: true

require_dependency "strails/backend_controller"

module Strails
  module Backend
    class VariantsController < BackendController
      before_action :set_product
      before_action :set_variant, only: %i[show edit update destroy]

      def index
        @variants = @product.variants
      end

      def show
        redirect_to edit_backend_product_variant_path(@product, @variant)
      end

      def new
        @variant = @product.variants.build
        @option_values = OptionValue.all
      end

      def edit; end

      def create
        @variant = @product.variants.build(variant_params)

        option_values = OptionValue.where(id: option_value_params[:option_value_ids])
        @variant.option_values = option_values unless option_values.empty?

        if @variant.save
          redirect_to backend_product_variants_path(@product),
                      notice: t("successfully_created", model_name: translated_model_name("variant"))
        else
          @option_values = OptionValue.all
          render :new
        end
      end

      def update
        if @variant.update(variant_params)
          redirect_to backend_product_variant_path(@product, @variant),
                      notice: t("successfully_updated", model_name: translated_model_name("variant"))
        else
          render :edit
        end
      end

      def destroy
        if @variant.destroy
          redirect_to backend_product_variants_path(@product),
                      notice: t("successfully_destroyed", model_name: translated_model_name("variant"))
        else
          redirect_to backend_product_variant_path(@product, @variant),
                      error: t("errors.could_not_destroy", model_name: translated_model_name("variant"))
        end
      end

      private

      def set_variant
        @variant = @product.variants.find(params[:id])
      end

      def set_product
        @product = Product.find(params[:product_id])
      end

      def variant_params
        params.require(:variant).permit(:sku, :price)
      end

      def option_value_params
        params.require(:variant).permit(option_value_ids: [])
      end
    end
  end
end

app/controllers/strails/backend_controller.rb
# frozen_string_literal: true

require_dependency "strails/application_controller"

module Strails
  class BackendController < ApplicationController
    include Croutons::Controller

    layout "strails/backend"
  end
end

app/helpers/strails/backend/dashboard_helper.rb
# frozen_string_literal: true

module Strails
  module Backend
    module DashboardHelper
    end
  end
end

app/helpers/strails/backend/option_types_helper.rb
# frozen_string_literal: true

module Strails
  module Backend
    module OptionTypesHelper
    end
  end
end

app/helpers/strails/backend/option_values_helper.rb
# frozen_string_literal: true

module Strails
  module Backend
    module OptionValuesHelper
    end
  end
end

app/helpers/strails/backend/products_helper.rb
# frozen_string_literal: true

module Strails
  module Backend
    module ProductsHelper
      def option_type_checkbox(form, option_type)
        id = option_type.id
        checkbox_id = "option-type-#{id}-checkbox"
        onclick = "checkOptionValues(#{id})"

        checkbox = form.check_box("option_type_#{id}",
                                  { class: "form-check-input", id: checkbox_id, onclick: onclick },
                                  id,
                                  nil)
        label = form.label(checkbox_id,
                           content_tag(:strong, option_type.pretty_name),
                           class: "form-check-label")
        checkbox + label
      end

      def option_value_checkboxes(form, option_values)
        option_type_id = option_values.first.option_type.id
        list_id = "option-values-for-option-type-#{option_type_id}"

        content_tag(:ul, class: "list-unstyled mb-3 pl-3", id: list_id) do
          capture do
            option_values.each do |option_value|
              concat(content_tag(:li, option_value_checkbox(form, option_value)))
            end
          end
        end
      end

      def option_value_checkbox(form, option_value)
        id = option_value.id
        checkbox_id = "option-value-#{id}-checkbox"
        onclick = "checkOptionType(#{option_value.option_type.id})"

        checkbox = form.check_box(:option_value_ids,
                                  { multiple: true, class: "form-check-input", id: checkbox_id, onclick: onclick },
                                  id,
                                  nil)
        label = form.label(checkbox_id,
                           option_value.pretty_name,
                           class: "form-check-label")
        checkbox + label
      end
    end
  end
end

app/helpers/strails/backend/variants_helper.rb
# frozen_string_literal: true

require "byebug"

module Strails
  module Backend
    module VariantsHelper
      def display_variant_extra_price(variant)
        extra_price = variant.extra_price
        return if extra_price.zero?

        content_tag(:span, class: extra_price.positive? ? "text-success" : "text-danger") do
          "#{'+' if extra_price.positive?}#{number_to_currency(extra_price)}"
        end
      end
    end
  end
end

app/helpers/strails/backend_helper.rb
# frozen_string_literal: true

module Strails
  module BackendHelper
  end
end

app/views/strails/backend/variants/_form.html.erb
<%= form_with(model: [:backend, product, variant], local: true) do |form| %>
  <%= error_messages_for(variant) %>

  <div class="form-group">
    <%= form.label :sku %>
    <%= form.text_field :sku, class: "form-control", autocomplete: "off" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text">$</span>
      </div>
      <%= form.number_field :price, step: "0.01", class: "form-control" %>
    </div>
  </div>

  <% if variant.new_record? %>
    <div class="form-group">
      <%= form.label :option_values %>
      <%= form.collection_select(:option_value_ids, @option_values, :id, :pretty_full, {}, { multiple: true, data: { "live-search": true }, class: "form-control selectpicker" }) %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit class: "btn-submit" %>

    <% if variant.persisted? %>
      <%= link_to(backend_product_variant_path(product, variant), method: :delete, class: "btn-destroy ml-3") do %>
        <%= material_icon "delete" %> <%= t("destroy") %>
      <% end %>
    <% end %>

    <%= link_to(backend_product_variants_path(product), class: "btn-cancel ml-3") do %>
      <%= material_icon "clear" %> <%= t("cancel") %>
    <% end %>
  </div>
<% end %>

app/views/strails/backend/variants/edit.html.erb
<div class="card">
  <div class="card-header">
    <h3><%= @variant.sku %></h3>
  </div>
  <div class="card-body">
    <%= render 'form', product: @product, variant: @variant %>
  </div>
</div>

app/views/strails/backend/variants/index.html.erb
<div class="variants">
  <div class="card">
    <div class="card-header">
      <h3><%= translated_model_name("variant", plural: true) %></h3>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th class="sku"><%= translated_model_attribute("variant", "sku") %></th>
              <% @product.option_types.each do |option_type| %>
                <th class="option-type"><%= option_type.pretty_name %></th>
              <% end %>
              <th class="price"><%= translated_model_attribute("variant", "price") %></th>
              <th class="extra-price"><%= translated_model_attribute("variant", "extra_price") %></th>
              <th class="actions actions-2"><%= t("actions") %></th>
            </tr>
          </thead>

          <tbody>
            <% @variants.each do |variant| %>
              <tr>
                <td class="sku"><%= variant.sku %></td>
                <% @product.option_types.each do |option_type| %>
                  <% if variant.option_types.include? option_type %>
                    <td class="option-value"><%= variant.option_value_from_option_type(option_type).pretty_name %></td>
                  <% else %>
                    <td class="option-value-missing">-</td>
                  <% end %>
                <% end %>
                <td class="price"><%= number_to_currency(variant.price) %></td>
                <td class="extra-price"><%= display_variant_extra_price(variant) %></td>
                <td class="actions actions-2">
                  <%= link_to material_icon("edit"), edit_backend_product_variant_path(@product, variant), class: "btn-edit btn-sm" %>
                  <%= link_to material_icon("delete"), backend_product_variant_path(@product, variant), method: :delete, class: "btn-destroy btn-sm" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <%= link_to(new_backend_product_variant_path(@product), class: "btn-new") do %>
        <%= material_icon("add") %> <%= t("new_variant") %>
      <% end %>
    </div>
  </div>
</div>

<%= content_for :content_navigation do %>
  <%= active_link_to(edit_backend_product_path(@product), active: :exact) do %>
    <%= material_icon "edit" %> <%= t("details") %>
  <% end %>
  <%= active_link_to(backend_product_variants_path(@product), active: :inclusive) do %>
    <%= material_icon "view_list" %> <%= translated_model_name("variant", plural: true) %>
  <% end %>
<% end %>

app/views/strails/backend/variants/new.html.erb
<div class="card">
  <div class="card-header">
    <h3><%= t("new_variant") %></h3>
  </div>
  <div class="card-body">
    <%= render 'form', product: @product, variant: @variant %>
  </div>
</div>